var devs = [
  {
  id: '1',
  image: "./images/photosnap.svg",
  nameImage: 'Photosnap',
  work: 'Senior Frontend Developer',
  time: '1d ago',
  mode: 'Full Time',
  country: 'USA only',
  type: 'Frontend',
  level: 'Senior',
  work1: 'HTML',
  work2: 'CSS',
  work3: 'JavaScript'
},
{
  id: '2',
  image: './images/manage.svg',
  nameImage: 'Manage',
  work: 'Fullstack Developer',
  time: '1d ago',
  mode: 'Part Time',
  country: 'Remote',
  type: 'Fullstack',
  level: 'Midweight',
  work1: 'Python',
  work2: 'React',
},
{
  id: '3',
  image: './images/account.svg',
  nameImage: 'Account',
  work: 'Junior Frontend Developer',
  time: '2d ago',
  mode: 'Part Time',
  country: 'USA only',
  type: 'Frontend',
  level: 'Junior',
  work1: 'React',
  work2: 'Sass',
  work3: 'JavaScript',
},
{
  id: '4',
  image: './images/myhome.svg',
  nameImage: 'MyHome',
  work: 'Junior Frontend Developer',
  time: '5d ago',
  mode: 'Part Time',
  country: 'USA only',
  type: 'Frontend',
  level: 'Junior',
  work1: 'CSS',
  work2: 'JavaScript',
},
{
  id: '5',
  image: './images/loop-studios.svg',
  nameImage: 'Loop Studios',
  work: 'Software Engineer',
  time: '1w ago',
  mode: 'Full Time',
  country: 'Worldwide',
  type: 'Fullstack',
  level: 'Midweight',
  work1: 'Javascript',
  work2: 'Sass',
  work3: 'Ruby',
},
{
  id: '6',
  image: './images/faceit.svg',
  nameImage: 'Facelt',
  work: 'Junior Backend Developer',
  time: '2w ago',
  mode: 'Part Time',
  country: 'UK only',
  type: 'Backend',
  level: 'Junior',
  work1: 'Ruby',
  work2: 'ROR',
},
{
  id: '7',
  image: './images/shortly.svg',
  nameImage: 'Shortly',
  work: 'Junior Developer',
  time: '2w ago',
  mode: 'Full Time',
  country: 'Worldwide',
  type: 'Frontend',
  level: 'Junior',
  work1: 'HTML',
  work2: 'Sass',
  work3: 'JavaScript',
},
{
  id: '8',
  image: './images/insure.svg',
  nameImage: 'Insure',
  work: 'Junior Frontend Developer',
  time: '2w ago',
  mode: 'Full Time',
  country: 'USA only',
  type: 'Frontend',
  level: 'Junior',
  work1: 'Vue',
  work2: 'JavaScript',
  work3: 'Sass',
},
{
  id: '9',
  image: './images/eyecam-co.svg',
  nameImage: 'Eyecam Co',
  work: 'Full Stack Engineer',
  time: '3w ago',
  mode: 'Full Time',
  country: 'Worldwide',
  type: 'Fullstack',
  level: 'Midweight',
  work1: 'Django',
  work2: 'JavaScript',
  work3: 'Python',
},
{
  id: '10',
  image: './images/the-air-filter-company.svg',
  nameImage: 'The Air Filter Company',
  work: 'Front-end Dev',
  time: '1mo ago',
  mode: 'Part Time',
  country: 'Worldwide',
  type: 'Frontend',
  level: 'Junior',
  work1: 'React',
  work2: 'Sass',
  work3: 'JavaScript',
},
]