devs = [
  {
  id: '1',
  image: 'developer',
  nameImage: 'Photosnap',
  work: 'Senior Frontend Developer',
  time: '1d ago',
  mode: 'Full Time',
  country: 'USA only',
  type: 'Frontend',
  leve: 'Senior',
  work1: 'HTML',
  work2: 'CSS',
  work3: 'JavaScript'
},
{
  id: '2',
  image: 'manage',
  nameImage: 'Manage',
  work: 'Fullstack Developer',
  time: '1d ago',
  mode: 'Part Time',
  country: 'Remote',
  type: 'Fullstack',
  leve: 'Midweight',
  work1: 'Python',
  work2: 'React',
},
{
  id: '3',
  image: 'account',
  nameImage: 'Account',
  work: 'Junior Frontend Developer',
  time: '2d ago',
  mode: 'Part Time',
  country: 'USA only',
  type: 'Frontend',
  leve: 'Junior',
  work1: 'React',
  work2: 'Sass',
  work3: 'JavaScript',
},
{
  id: '4',
  image: 'myhome',
  nameImage: 'MyHome',
  work: 'Junior Frontend Developer',
  time: '5d ago',
  country: 'USA only',
  type: 'Frontend',
  leve: 'Junior',
  work1: 'CSS',
  work2: 'JavaScript',
},
{
  id: '5',
  image: 'loop',
  nameImage: 'Loop Studios',
  work: 'Software Engineer',
  time: '1w ago',
  mode: 'Full Time',
  country: 'Worldwide',
  type: 'Fullstack',
  leve: 'Midweight',
  work1: 'Javascript',
  work2: 'Sass',
  work3: 'Ruby',
},
{
  id: '6',
  image: 'studios',
  nameImage: 'Facelt',
  work: 'Junior Backend Developer',
  time: '2w ago',
  country: 'UK only',
  type: 'Backend',
  leve: 'Junior',
  work1: 'Ruby',
  work2: 'ROR',
},
{
  id: '7',
  image: 'shortly',
  nameImage: 'Shortly',
  work: 'Junior Developer',
  time: '2w ago',
  mode: 'Full Time',
  country: 'Worldwide',
  type: 'Frontend',
  leve: 'Junior',
  work1: 'HTML',
  work2: 'Sass',
  work3: 'JavaScript',
},
]